//! Which sixteenth notes are kick drums — the Conductor's scoring targets.
//!
//! GENERATED by `tools/make_conductor_music.py`. Do not edit: the same script
//! renders the audio from this table, so a hand edit here would silently score
//! the player against a rhythm the song does not play. Change the patterns in
//! the script and re-run it.
//!
//! Only KICKS are targets. The snare on 2 and 4, the hats on the eighths and
//! the bass are there to make a bar feel like music, and deliberately do not
//! score — a grid where every click is a target is a mashing test, not a
//! rhythm.

/// Bars in the loop. The pattern repeats every this many bars.
pub const CONDUCTOR_BEATMAP_BARS: u32 = 8;
/// Sixteenth notes per bar.
pub const CONDUCTOR_SLOTS_PER_BAR: u32 = 16;
/// Sixteenths per quarter-note beat.
pub const CONDUCTOR_SLOTS_PER_BEAT: u32 = 4;

/// The sixteenth the wave warning sounds on — the "and of 4".
///
/// Never a kick in any bar (the generator asserts it), so the ear can tell
/// "yours to hit" from "coming at you" by WHERE it lands as well as by timbre.
pub const CONDUCTOR_WAVE_CUE_SLOT: u32 = 14;

/// Bit `s` set means sixteenth `s` of that bar is a kick.
pub const CONDUCTOR_KICKS: [u16; 8] = [
    0b0000000100000001, // bar 0: x.......x.......
    0b0001000100000001, // bar 1: x.......x...x...
    0b0000000100000101, // bar 2: x.x.....x.......
    0b0000010001000001, // bar 3: x.....x...x.....
    0b0000000100000001, // bar 4: x.......x.......
    0b0001000100010001, // bar 5: x...x...x...x...
    0b0001010100000001, // bar 6: x.......x.x.x...
    0b0001000101000001, // bar 7: x.....x.x...x...
];

/// Total targets in one loop — what the resonance requirement is tuned against.
pub const CONDUCTOR_KICKS_PER_LOOP: u32 = 25;

/// Is sixteenth `slot` of bar `bar` (both within the loop) a scoring target?
#[inline]
pub fn is_kick(bar: u32, slot: u32) -> bool {
    if slot >= CONDUCTOR_SLOTS_PER_BAR {
        return false;
    }
    let mask = CONDUCTOR_KICKS[(bar % CONDUCTOR_BEATMAP_BARS) as usize];
    mask & (1u16 << slot) != 0
}
