use quartz::*;
use std::sync::{Arc, Mutex};

use crate::constants::*;
use crate::state::*;
use super::beatmap::*;
#[allow(unused_imports)]
use super::*;

/// The Conductor: the run's second boss, fought to a bar.
///
/// ## The verb
///
/// Every other boss asks where you swing. This one asks **when you let go**.
/// Releasing your tether ON A KICK DRUM HIT earns a stack of Resonance; seven
/// stacks arm the weakpoint for five seconds, and a buffed hit lands real
/// damage.
///
/// The targets are the kicks, NOT every beat. Which sixteenths are kicks
/// changes bar to bar — pairs, syncopation, a four-on-the-floor bar, and two
/// deliberately sparse bars to rest in — and the map lives in `beatmap.rs`,
/// generated by the same script that renders the audio so the two cannot
/// disagree. Scoring every beat made this roughly two targets a second with a
/// penalty for missing one, which is a mashing test rather than a rhythm.
///
/// A bar in which the player scores nothing while attached costs a stack. A
/// bar in which they score anything costs nothing, so reading the rhythm
/// correctly never takes progress away.
///
/// ## Why the numbers are what they are
///
/// A bar is four beats of 36 ticks — 144 ticks, within 10% of the 160-tick
/// pattern cooldown every other boss attacks on. So ONE ATTACK PER BAR puts the
/// rhythm and the house attack cadence in agreement without bending either, and
/// telegraphing on beat 3 for a hit on the downbeat gives 72 ticks of warning,
/// essentially the 60 the Colossus and the Serpent both use.
///
/// It is the second fight of the run, so the cycle is faster and each hit
/// cheaper than the late bosses: its job is to teach timing, not to be a wall.
///
/// ## The beat has to be visible
///
/// Two visual channels carry it — the bob crossing the case's scale, and the
/// spars flashing — plus a ring leaving the core on every downbeat. That is not
/// decoration over an audio cue: this game shipped for weeks with silent audio
/// on Android and mobile audio can lag regardless, so a rhythm fight that can
/// only be heard is a rhythm fight that cannot be played.
pub(crate) fn tick_conductor(c: &mut Canvas, st: &Arc<Mutex<State>>) {
    // ── Gates ────────────────────────────────────────────────────────────
    let (active, dead, stasis, spawned) = {
        let s = st.lock().unwrap();
        (s.boss_active, s.dead, s.boss_stasis_active, s.boss_spawned)
    };
    if !active || dead || stasis {
        // Clean up a fight that was running, but only when there is something
        // to clean: this runs every frame for the whole run whenever the NEXT
        // boss is the Conductor, and `hide_conductor` builds thirteen object
        // names with `format!` each time. Unconditionally it cost enough to
        // push the deadlock regression test past its ninety-second timeout.
        //
        // One object lookup is the whole check, and the core's visibility is
        // exactly "did this fight put anything on screen".
        if !active || dead {
            let showing = c
                .get_game_object("conductor_core")
                .map(|o| o.visible)
                .unwrap_or(false);
            if showing {
                hide_conductor(c);
            }
        }
        return;
    }

    if !spawned {
        spawn_conductor(c, st);
        return;
    }

    // Snapshot everything the tick needs, then DROP the lock before touching
    // the canvas. Holding a State guard across `get_game_object_mut` is what
    // deadlocked the buff tick; the rule is one lock, one purpose, released.
    let (px, py, hooked, hp) = {
        let s = st.lock().unwrap();
        (s.px, s.py, s.hooked, s.boss_hp)
    };
    let core = c
        .get_game_object("conductor_core")
        .map(|o| (o.position.0 + CONDUCTOR_CORE_SIZE * 0.5, o.position.1 + CONDUCTOR_CORE_SIZE * 0.5))
        .unwrap_or((arena_center_x(c), BOSS_Y_CENTER));
    let buffed = { st.lock().unwrap().buff_active() };

    // Phase two speeds the bar up, so the music has to change with it — the
    // two loops are the same piece at 100 and 120 BPM, which are exactly the
    // two beat intervals. Driven by the same HP test that sets the tempo, so
    // the track and the grid cannot disagree about which phase this is.
    if hp <= BOSS_MAX_HP / 2 {
        crate::scenes::game::switch_game_bgm(
            c, BGM_TRACK_CONDUCTOR_P2, ASSET_CONDUCTOR_BGM_P2, CONDUCTOR_BGM_VOL);
    }

    let beat_landed = tick_beat(st, hp);
    tick_release_scoring(c, st, hooked, beat_landed);
    tick_attack_director(c, st, beat_landed, core, (px, py));
    tick_weakpoint(c, st, buffed, core, (px, py));
    {
        // The guard pulses harder on the scoring beats, so it is one more
        // channel carrying the kick map rather than a separate rhythm to read.
        let on_target = {
            let s = st.lock().unwrap();
            kick_proximity(loop_slot_position(
                s.conductor_loop_bar, s.conductor_beat_in_bar, s.conductor_beat_phase))
        };
        tick_eq_guard(c, st, core, (px, py), beat_landed, on_target);
        tick_beat_nodes(c, st, on_target);
    }
    tick_contact(c, st, core, (px, py));
    draw_conductor(c, st, core);
}

/// Place the body, the spars and the name, and start the bar.
fn spawn_conductor(c: &mut Canvas, st: &Arc<Mutex<State>>) {
    let name = {
        let mut s = st.lock().unwrap();
        s.boss_spawned = true;
        s.boss_kind.name()
    };

    let cx = arena_center_x(c);
    let spawn = (cx - CONDUCTOR_CORE_SIZE * 0.5, BOSS_Y_CENTER - CONDUCTOR_CORE_SIZE * 0.5);
    for id in ["boss"] {
        // The generic `boss` square is the Conductor's hitbox and HP carrier,
        // but the metronome is what the player sees, so the square is placed
        // and left invisible.
        if let Some(o) = c.get_game_object_mut(id) {
            o.position = spawn;
            o.visible = false;
        }
    }
    if let Some(o) = c.get_game_object_mut("conductor_core") {
        o.position = spawn;
        o.visible = true;
    }
    if let Some(o) = c.get_game_object_mut("conductor_bob") {
        o.visible = true;
    }
    for i in 0..CONDUCTOR_SPARS {
        if let Some(o) = c.get_game_object_mut(&format!("conductor_spar_{i}")) {
            o.visible = true;
        }
    }

    if let Ok(font) = Font::from_bytes(include_bytes!("../../../../assets/font.ttf")) {
        let sc = c.virtual_scale();
        if let Some(obj) = c.get_game_object_mut("boss_name_text") {
            obj.set_drawable(Box::new(crate::objects::ui_text_spec(
                name, &font, 42.0 * sc, Color(90, 220, 200, 255), 1000.0 * sc,
            )));
        }
    }

    // The fight's own loop, at the fight's own tempo.
    crate::scenes::game::switch_game_bgm(
        c, BGM_TRACK_CONDUCTOR_P1, ASSET_CONDUCTOR_BGM_P1, CONDUCTOR_BGM_VOL);

    let mut s = st.lock().unwrap();
    s.boss_beat_interval = CONDUCTOR_BEAT_TICKS;
    s.boss_beat_ticks = s.boss_beat_interval;
    s.conductor_beat_in_bar = 0;
    s.conductor_loop_bar = 0;
    s.conductor_bar_hits = 0;
    s.conductor_last_kick = -1;
    s.conductor_cue_delay = 0;
    s.conductor_wave_shape = 0;
    // Seeded from the run so a retry is not a replay of the same attack order,
    // but fixed within a run so the headless harness stays reproducible.
    s.conductor_rng = 0x9E37_79B9_7F4A_7C15 ^ (s.boss_hp as u64).wrapping_mul(0x5851_F42D);
    s.conductor_beat_phase = 0.0;
    s.conductor_beat_clock = None;
    s.conductor_attack = 0;
    s.conductor_attack_ticks = 0;
    s.conductor_telegraph = 0;
    s.boss_resonance = 0;
}

/// Advance the bar. Returns true on the tick a beat lands.
/// What advancing the beat clock by `dt` seconds does.
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct BeatAdvance {
    /// How far through the beat afterwards, 0..1.
    pub phase: f32,
    /// Whether a beat landed during this step.
    pub landed: bool,
    /// Whether the gap was long enough to be an absence rather than a frame,
    /// so the clock re-based instead of catching up.
    pub rebased: bool,
}

/// Advance the beat by REAL elapsed time.
///
/// Counting ticks assumes every tick is exactly 1/60s. It is not: a dropped
/// frame is time that passed without a tick, and the audio — which runs on its
/// own thread against the wall clock — does not miss it. Counting ticks
/// therefore falls permanently behind the music, with nothing to resynchronise
/// it, and on a boss scored against a +/-100ms window that eventually marks
/// correct releases as misses.
///
/// Advancing by `dt` keeps the beat on the same clock as the sound. The
/// fractional remainder is CARRIED, not discarded, so the phase is exact over
/// any number of beats rather than rounding down once per beat.
///
/// A gap longer than `max_dt` is an absence (a pause, a scene load, a stall),
/// not a frame: the clock re-bases rather than firing every beat it missed.
pub(crate) fn advance_beat(phase: f32, dt: f32, beat_secs: f32, max_dt: f32) -> BeatAdvance {
    let beat_secs = beat_secs.max(1e-4);
    if !(dt.is_finite()) || dt < 0.0 || dt > max_dt {
        return BeatAdvance { phase, landed: false, rebased: true };
    }
    let advanced = phase + dt / beat_secs;
    if advanced >= 1.0 {
        // Carry the remainder: dropping it would lose up to a frame of phase
        // on every beat, which is the same drift by a slower route.
        BeatAdvance { phase: advanced.fract(), landed: true, rebased: false }
    } else {
        BeatAdvance { phase: advanced, landed: false, rebased: false }
    }
}

/// Seconds per beat at a tick-denominated interval.
pub(crate) fn beat_seconds(interval_ticks: u32) -> f32 {
    interval_ticks.max(1) as f32 / TICKS_PER_SECOND
}

fn tick_beat(st: &Arc<Mutex<State>>, hp: i32) -> bool {
    let mut s = st.lock().unwrap();

    // Phase two tightens the bar once the boss is below half. Set every beat
    // rather than once at the threshold, so it is correct however HP got there.
    //
    // NOT while a crescendo is running: that attack IS a tempo ramp, and
    // rewriting the interval from HP every beat flattened it back out, so the
    // attack did nothing a player could hear or see.
    let crescendo = s.conductor_attack == 3 && s.conductor_telegraph == 0;
    if !crescendo {
        s.boss_beat_interval = if hp <= BOSS_MAX_HP / 2 {
            CONDUCTOR_BEAT_TICKS_P2
        } else {
            CONDUCTOR_BEAT_TICKS
        };
    }

    // Real elapsed time since the clock was last advanced.
    let now = std::time::Instant::now();
    let dt = match s.conductor_beat_clock {
        Some(prev) => now.duration_since(prev).as_secs_f32(),
        // First tick of the fight: start the clock, do not advance it.
        None => f32::INFINITY,
    };
    s.conductor_beat_clock = Some(now);

    let step = advance_beat(
        s.conductor_beat_phase,
        dt,
        beat_seconds(s.boss_beat_interval),
        CONDUCTOR_BEAT_MAX_DT,
    );
    s.conductor_beat_phase = step.phase;

    // `boss_beat_ticks` is still what the scoring and the visuals read, so it
    // is DERIVED from the phase rather than being a second clock that could
    // disagree with it.
    let interval = s.boss_beat_interval.max(1);
    s.boss_beat_ticks =
        (((1.0 - step.phase) * interval as f32).round() as u32).clamp(0, interval);

    if step.landed {
        s.conductor_beat_in_bar = (s.conductor_beat_in_bar + 1) % CONDUCTOR_BEATS_PER_BAR;
        // Turn of the bar: step the loop too, so the kick map the fight scores
        // against stays on the same bar the song is playing. Derived from the
        // one clock rather than timed separately — a second timer here is
        // exactly how the drums and the targets would drift apart.
        if s.conductor_beat_in_bar == 0 {
            s.conductor_loop_bar = (s.conductor_loop_bar + 1) % CONDUCTOR_BEATMAP_BARS;
        }
    }
    step.landed
}

/// Where the fight is in the music, as a sixteenth note.
///
/// Returns the global slot index within the loop as a FRACTION: bar 2's
/// "1-e" is 2*16 + 1 = 33.0 exactly on the hit, 33.5 halfway to the next
/// sixteenth. Everything about targeting is expressed against this one number,
/// so there is no second notion of "where we are" to fall out of step.
pub(crate) fn loop_slot_position(bar: u32, beat_in_bar: u32, phase: f32) -> f32 {
    let bar = bar % CONDUCTOR_BEATMAP_BARS;
    let within_bar = (beat_in_bar % CONDUCTOR_BEATS_PER_BAR) as f32
        + phase.clamp(0.0, 1.0);
    bar as f32 * CONDUCTOR_SLOTS_PER_BAR as f32
        + within_bar * CONDUCTOR_SLOTS_PER_BEAT as f32
}

/// Total sixteenths in one pass of the loop.
pub(crate) fn loop_slots() -> u32 {
    CONDUCTOR_BEATMAP_BARS * CONDUCTOR_SLOTS_PER_BAR
}

/// The nearest kick to `pos`, as (its global slot index, distance in slots).
///
/// Distance is signed-magnitude around the loop, so a release just before the
/// loop seam correctly finds the kick on the other side of it rather than
/// measuring the long way round and calling a perfect release a miss.
pub(crate) fn nearest_kick(pos: f32) -> (u32, f32) {
    let total = loop_slots();
    let mut best = (0u32, f32::INFINITY);
    for g in 0..total {
        let bar = g / CONDUCTOR_SLOTS_PER_BAR;
        let slot = g % CONDUCTOR_SLOTS_PER_BAR;
        if !is_kick(bar, slot) {
            continue;
        }
        let raw = (g as f32 - pos).abs();
        let d = raw.min(total as f32 - raw); // around the seam
        if d < best.1 {
            best = (g, d);
        }
    }
    best
}

/// How a release at this instant scores against the KICK MAP.
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) enum ReleaseScore {
    /// Inside the window of a kick: which one, so it cannot be claimed twice.
    Hit { kick: u32 },
    /// Not near any kick.
    Miss,
}

/// Score a release against the drums.
///
/// Targets are the kick drum hits only — never the snare, the hats or the
/// bass. The old version scored EVERY beat, which at 100-120 BPM is roughly
/// two targets a second with a penalty for missing one, and that is a button-
/// mashing test rather than a rhythm to read.
///
/// The test is symmetric in time and resolved IMMEDIATELY in both directions,
/// which is what let the two-stage "arm and wait for the beat" dance go: the
/// kick map says where the next kick is, so an early release can be judged the
/// moment it happens instead of being held open and confirmed later.
///
/// `ticks_per_slot` converts sixteenths to ticks so the window stays +/-100ms
/// at either tempo. No two kicks in the map are closer than two sixteenths
/// (15 ticks at 120 BPM, 18 at 100), so a +/-6 tick window can never straddle
/// two targets.
pub(crate) fn score_release_slot(pos: f32, ticks_per_slot: f32, window: u32) -> ReleaseScore {
    let (kick, dist_slots) = nearest_kick(pos);
    if !dist_slots.is_finite() {
        return ReleaseScore::Miss;
    }
    let dist_ticks = dist_slots * ticks_per_slot.max(1e-3);
    if dist_ticks <= window as f32 {
        ReleaseScore::Hit { kick }
    } else {
        ReleaseScore::Miss
    }
}

/// Score the player's releases against the beat.
///
/// Targets are the KICK DRUM hits in `beatmap.rs`, not every beat. The window
/// is symmetric — human timing error falls on both sides of a hit — and it is
/// resolved the instant the release happens, because the kick map already says
/// where the next kick is.
///
/// A kick can only be claimed once (`conductor_last_kick`): without that, two
/// releases either side of the same hit both land inside its window and score
/// twice, which pays for exactly the mashing the map exists to prevent.
fn tick_release_scoring(
    c: &mut Canvas, st: &Arc<Mutex<State>>, hooked: bool, beat_landed: bool,
) {
    // What the player's own pulse should say this tick, decided under the lock
    // and fired after it: green for a release that scored, red for a stack
    // lost. Told ON THE PLAYER because that is where they are looking at the
    // moment they let go — the meter and the nodes both report it afterwards,
    // and afterwards is too late to learn timing from.
    let mut pulse: Option<bool> = None;
    let mut s = st.lock().unwrap();

    let released = s.boss_was_hooked && !hooked;
    s.boss_was_hooked = hooked;

    if released {
        let pos = loop_slot_position(
            s.conductor_loop_bar, s.conductor_beat_in_bar, s.conductor_beat_phase);
        let ticks_per_slot =
            s.boss_beat_interval.max(1) as f32 / CONDUCTOR_SLOTS_PER_BEAT as f32;
        if let ReleaseScore::Hit { kick } =
            score_release_slot(pos, ticks_per_slot, CONDUCTOR_RELEASE_WINDOW)
        {
            if s.conductor_last_kick != kick as i32 {
                s.conductor_last_kick = kick as i32;
                s.boss_resonance =
                    (s.boss_resonance + 1).min(CONDUCTOR_RESONANCE_REQUIRED);
                s.conductor_bar_hits += 1;
                pulse = Some(true);
            }
        }
    }

    if beat_landed {
        // The drain, once per bar, on the downbeat.
        //
        // It now costs a stack only for a bar in which the player scored
        // NOTHING while attached — not for every bar they were attached at the
        // turn of. With seven stacks to collect and bars that deliberately
        // contain as few as two targets, charging a stack for a bar the player
        // played well would take progress away for reading the rhythm
        // correctly, which is the opposite of the lesson.
        if s.conductor_beat_in_bar == 0 {
            if s.boss_resonance > 0 && hooked && s.conductor_bar_hits == 0 {
                s.boss_resonance -= 1;
                pulse = Some(false);
            }
            s.conductor_bar_hits = 0;
        }

        if s.boss_resonance >= CONDUCTOR_RESONANCE_REQUIRED {
            // Arm ONCE and spend the meter. Leaving the meter full re-armed the
            // window on every following beat, so it never ran out; spending it
            // is what makes `CONDUCTOR_WINDOW_TICKS` mean five seconds.
            s.boss_flare_window_ticks = CONDUCTOR_WINDOW_TICKS;
            s.boss_resonance = 0;
            s.conductor_bar_hits = 0;
        }
    }

    if s.boss_flare_window_ticks > 0 {
        s.boss_flare_window_ticks -= 1;
    }
    let at = (s.px, s.py);
    drop(s);
    if let Some(hit) = pulse {
        crate::scenes::game::boss::common::spawn_beat_pulse(c, st, at, hit);
    }
}

/// Choose, telegraph and run one attack per bar.
fn tick_attack_director(
    c: &mut Canvas,
    st: &Arc<Mutex<State>>,
    beat_landed: bool,
    core: (f32, f32),
    player: (f32, f32),
) {
    // Queue on the telegraph beat, fire on the downbeat.
    if beat_landed {
        let (beat, attack, hp) = {
            let s = st.lock().unwrap();
            (s.conductor_beat_in_bar, s.conductor_attack, s.boss_hp)
        };
        if attack == 0 && beat == CONDUCTOR_TELEGRAPH_BEAT {
            let mut s = st.lock().unwrap();
            // Crescendo only exists in phase two: the fight gains an attack as
            // it goes rather than shuffling the same three.
            let phase2 = hp <= BOSS_MAX_HP / 2;
            // From the Conductor's OWN stream. See `State::conductor_rng`:
            // this used to read `boss_phase`, which nothing in this fight ever
            // advances, so every roll came out 0 and two of the three attacks
            // were unreachable.
            let roll = (crate::state::lcg(&mut s.conductor_rng)
                * if phase2 { 3.0 } else { 2.0 }) as u32;
            let roll = roll.min(if phase2 { 2 } else { 1 });
            s.conductor_attack = (roll + 1) as u8;
            // Two beats of telegraph, so the tell lands on the bar the attack
            // fires on rather than floating free of the music.
            s.conductor_telegraph = s.boss_beat_interval * 2;
            s.conductor_attack_ticks = 0;
            s.conductor_bar_hit = false;
            s.conductor_wave_hit = 0;
            // How many waves. One is the common case early; phase two brings
            // doubles and triples, so the attack escalates with the fight
            // instead of the fight only getting faster.
            let roll = (crate::state::lcg(&mut s.conductor_rng) * 4.0) as u32 % 4;
            s.conductor_wave_count = if phase2 {
                match roll { 0 => 1, 1 | 2 => 2, _ => CONDUCTOR_WAVE_MAX }
            } else {
                match roll { 0 | 1 | 2 => 1, _ => 2 }
            };
            // Aim the sweep now, at telegraph time, so what the tell shows is
            // what the attack does. Deciding at fire time makes the tell a lie.
            s.conductor_bar_dir = if player.0 < core.0 { 1.0 } else { -1.0 };
            // Put the gap AWAY from the player, on the far side of the arena's
            // middle, so the attack is "get to the gap" rather than "happen not
            // to be in the way".
            //
            // Aiming it at the player's own Y made a stationary player
            // permanently safe — the headless bot parked on one node and took
            // zero damage across 4000 frames with the fight running. In a game
            // about swinging, an attack nobody has to move for is not an
            // attack.
            // Pick the volley's SHAPE. Tight shapes are held back for phase
            // two and for bigger volleys: three waves in three beats is a
            // real demand, and it should arrive as an escalation rather than
            // as the second thing the fight ever does.
            let shape_roll = (crate::state::lcg(&mut s.conductor_rng) * 4.0) as u32 % 4;
            s.conductor_wave_shape = if s.conductor_wave_count <= 1 {
                0
            } else if phase2 {
                (shape_roll % CONDUCTOR_WAVE_SHAPES.len() as u32) as u8
            } else {
                // Phase one: even, or the gentler of the two clustered shapes.
                match shape_roll % 3 { 0 => 0, 1 => 1, _ => 2 }
            };

            // Queue the volley announcement onto the next "and of 4", so it
            // arrives in the music rather than across it.
            let pos = loop_slot_position(
                s.conductor_loop_bar, s.conductor_beat_in_bar, s.conductor_beat_phase);
            let tps = s.boss_beat_interval.max(1) as f32 / CONDUCTOR_SLOTS_PER_BEAT as f32;
            s.conductor_cue_delay = ticks_to_slot(pos, CONDUCTOR_WAVE_CUE_SLOT, tps);

            let span = CONDUCTOR_BAR_SPAN * 0.5 - CONDUCTOR_BAR_GAP * 0.5;
            let mid = BOSS_ARENA_PLAY_MID_Y;
            let away = if player.1 > mid { -1.0 } else { 1.0 };
            s.conductor_bar_gap_y =
                (mid + away * span * 0.55).clamp(mid - span, mid + span);
        }
    }

    // Play the queued volley announcement when its sixteenth comes round.
    {
        let fire = {
            let mut s = st.lock().unwrap();
            if s.conductor_cue_delay > 0 {
                s.conductor_cue_delay -= 1;
                s.conductor_cue_delay == 0
            } else {
                false
            }
        };
        if fire {
            let vol = crate::scenes::game::helpers::sfx_vol(c, CONDUCTOR_WAVE_CUE_VOL);
            c.play_sound_bytes_with(
                ASSET_CONDUCTOR_WAVE_CUE, SoundOptions::new().volume(vol));
        }
    }

    // Run down the telegraph.
    let (telegraph, attack) = {
        let mut s = st.lock().unwrap();
        if s.conductor_telegraph > 0 {
            s.conductor_telegraph -= 1;
        }
        (s.conductor_telegraph, s.conductor_attack)
    };
    if attack == 0 || telegraph > 0 {
        return;
    }

    // Fire.
    let ticks = {
        let mut s = st.lock().unwrap();
        s.conductor_attack_ticks += 1;
        s.conductor_attack_ticks
    };
    match attack {
        1 => run_bar_line(c, st, ticks, core, player),
        2 => run_sustain(c, st, ticks),
        3 => run_crescendo(c, st, ticks, player, core),
        _ => {}
    }
}

/// A standing wave crosses the arena, ringing every tether node it reaches.
///
/// ## What it asks
///
/// Being ATTACHED when it arrives is the mistake — not being in its way. The
/// fight's verb is when you let go, and an attack you dodge by swinging to a
/// gap tests a different, generic skill; this one tests the same thing the
/// scoring does, so surviving it and scoring on it are the same action.
///
/// A node rings for `CONDUCTOR_RING_LEAD` of the wave's approach, which is the
/// telegraph: the thing in your hand starts screaming well before it strikes.
/// Ticks between successive waves, at this tempo.
///
/// Derived from the live beat interval so the volley stays on the grid when
/// phase two tightens the tempo. A fixed tick count would drift off the bar
/// exactly when the fight speeds up, and on this boss the beat is the thing
/// the player is reading.
pub(crate) fn wave_stagger(beat_interval: u32) -> u32 {
    beat_interval.max(1) * CONDUCTOR_WAVE_STAGGER_BEATS
}

/// How close the clock is to a scoring target, 1.0 ON the kick and 0.0 a
/// sixteenth or more away.
///
/// Drives the colour of the beat field and the spars. The fight was unreadable
/// without it: every beat looked identical, so "which of these is mine to hit"
/// had to be learned from the audio alone, and the whole point of the kick map
/// is that only some beats are targets.
pub(crate) fn kick_proximity(pos: f32) -> f32 {
    let (_, dist) = nearest_kick(pos);
    if !dist.is_finite() {
        return 0.0;
    }
    (1.0 - dist).clamp(0.0, 1.0)
}

/// Ticks from `pos` until sixteenth `target` of a bar comes round again.
///
/// Used to put the wave warning on the grid instead of playing it the instant
/// the attack is chosen. A warning that lands across the beat sounds like a
/// mistake in the music, and this fight asks the player to trust the music.
pub(crate) fn ticks_to_slot(pos: f32, target: u32, ticks_per_slot: f32) -> u32 {
    let spb = CONDUCTOR_SLOTS_PER_BAR as f32;
    let here = pos % spb;
    let mut delta = target as f32 - here;
    if delta <= 0.0 {
        delta += spb; // the next one, not the one that just went by
    }
    (delta * ticks_per_slot.max(1e-3)).round().max(1.0) as u32
}

/// The off-beat a wave's whoosh plays on, relative to the attack starting.
///
/// Half a beat BEFORE the wave itself launches. Two things at once: it is a
/// warning, and it is deliberately off the quarter-note grid the kick targets
/// sit on — so "this one is yours to hit" and "this one is coming at you" are
/// separated by WHERE they land as well as by how they sound.
pub(crate) fn wave_whoosh_tick(k: usize, beat_interval: u32, shape: u8) -> u32 {
    wave_launch_tick(k, beat_interval, shape).saturating_sub(beat_interval.max(1) / 2)
}

/// Beat offsets for volley shape `shape`.
pub(crate) fn wave_shape(shape: u8) -> [u32; 3] {
    CONDUCTOR_WAVE_SHAPES[(shape as usize) % CONDUCTOR_WAVE_SHAPES.len()]
}

/// When wave `k` of a volley launches, relative to the attack starting.
///
/// The offset comes from the volley's SHAPE rather than from a fixed stagger,
/// so a triple can arrive evenly, as a quick pair with room after, as a gap
/// then a pair, or as three in three beats. Still whole beats, so every launch
/// is on the grid.
pub(crate) fn wave_launch_tick(k: usize, beat_interval: u32, shape: u8) -> u32 {
    let offs = wave_shape(shape);
    let beats = offs[k.min(offs.len() - 1)];
    beats * beat_interval.max(1)
}

/// How long a volley of `count` waves takes, start to last wave clearing.
pub(crate) fn wave_attack_ticks(count: u8, beat_interval: u32, shape: u8) -> u32 {
    let last = count.max(1) as usize - 1;
    wave_launch_tick(last, beat_interval, shape) + CONDUCTOR_BAR_SWEEP_TICKS
}

fn run_bar_line(
    c: &mut Canvas,
    st: &Arc<Mutex<State>>,
    ticks: u32,
    core: (f32, f32),
    _player: (f32, f32),
) {
    let (dir, hooked, active_hook, nodes, previously_ringing, count, beat, shape) = {
        let s = st.lock().unwrap();
        (s.conductor_bar_dir, s.hooked, s.active_hook.clone(), s.live_hooks.clone(),
         s.conductor_ring_fx.clone(), s.conductor_wave_count.max(1),
         s.boss_beat_interval.max(1), s.conductor_wave_shape)
    };

    let half_w = BOSS_ARENA_HALF_W;
    let span = half_w * 2.0 + CONDUCTOR_BAR_THICKNESS * 2.0;

    // Where each live wave is, and which way it is going. Alternating
    // directions, so a multiple cannot be answered by drifting one way.
    // Each wave's whoosh, on the off-beat half a beat before it launches.
    // Equality rather than a range: `ticks` increments by one per tick, so this
    // fires exactly once per wave.
    for k in 0..count as usize {
        if ticks == wave_whoosh_tick(k, beat, shape) {
            let vol = crate::scenes::game::helpers::sfx_vol(c, CONDUCTOR_WAVE_HIT_VOL);
            c.play_sound_bytes_with(
                ASSET_CONDUCTOR_WAVE_HIT, SoundOptions::new().volume(vol));
        }
    }

    let mut waves: Vec<(usize, f32)> = Vec::new();
    for k in 0..count as usize {
        let launch = wave_launch_tick(k, beat, shape);
        if ticks < launch {
            continue;
        }
        let local = ticks - launch;
        let t = local as f32 / CONDUCTOR_BAR_SWEEP_TICKS as f32;
        if t > 1.0 {
            continue;
        }
        let d = if k % 2 == 0 { dir } else { -dir };
        let x = core.0 - d * (half_w + CONDUCTOR_BAR_THICKNESS) + d * t * span;
        waves.push((k, x));
    }

    // Draw one band per live wave, park the rest.
    let slots = ["conductor_bar_0_top", "conductor_bar_0_bot",
                 "conductor_bar_1_top", "conductor_bar_1_bot"];
    for (i, slot) in slots.iter().enumerate() {
        let live = waves.get(i).map(|(_, x)| *x);
        if let Some(o) = c.get_game_object_mut(slot) {
            match live {
                Some(x) => {
                    o.size = (CONDUCTOR_BAR_THICKNESS, CONDUCTOR_BAR_SPAN);
                    o.position = (
                        x - CONDUCTOR_BAR_THICKNESS * 0.5,
                        BOSS_ARENA_PLAY_MID_Y - CONDUCTOR_BAR_SPAN * 0.5,
                    );
                    o.visible = true;
                }
                None => {
                    o.visible = false;
                    o.size = (CONDUCTOR_DORMANT, CONDUCTOR_DORMANT);
                    o.position = (-9000.0, -9000.0);
                }
            }
        }
    }

    // Ring every node any wave is approaching, and note which wave — if any —
    // is close enough to strike the node the player is holding.
    let mut ringing: Vec<String> = Vec::new();
    let mut struck_by: Option<usize> = None;
    for id in &nodes {
        let Some(obj) = c.get_game_object(id) else { continue; };
        if !obj.visible { continue; }
        let nx = obj.position.0 + obj.size.0 * 0.5;
        let nr = obj.size.0.max(obj.size.1) * 0.5;

        // The NEAREST wave owns the node's warning, so with several in flight
        // the ring reflects the next one to arrive rather than flickering
        // between them.
        let mut best = 0.0f32;
        for (k, wx) in &waves {
            let gap = (nx - wx).abs();
            if gap <= CONDUCTOR_RING_LEAD {
                best = best.max(1.0 - gap / CONDUCTOR_RING_LEAD);
            }
            if hooked && *id == active_hook && gap <= CONDUCTOR_WAVE_BAND {
                struck_by = Some(*k);
            }
        }
        if best > 0.0 {
            c.attach_effect(
                id,
                Effect::SonicRing { intensity: best },
                crate::scenes::game::fx::lin(CONDUCTOR_SONIC_RGB),
                (nr * CONDUCTOR_SONIC_FX_SCALE, nr * CONDUCTOR_SONIC_FX_SCALE),
            );
            ringing.push(id.clone());
        }
    }

    // Release anything that has stopped ringing, so a node the waves have
    // passed goes quiet — and so a recycled node never inherits the effect.
    for id in &previously_ringing {
        if !ringing.contains(id) {
            c.clear_effect(id);
        }
    }
    st.lock().unwrap().conductor_ring_fx = ringing;

    if let Some(k) = struck_by {
        // One strike per WAVE. A single shared latch would make every wave
        // after the first harmless, which is the whole point of a multiple.
        let first = {
            let mut s = st.lock().unwrap();
            let bit = 1u8 << (k.min(7) as u8);
            let f = s.conductor_wave_hit & bit == 0;
            s.conductor_wave_hit |= bit;
            f
        };
        if first {
            c.run(Action::ReleaseGrapple { target: Target::name("player") });
            hit_player(c, st);
        }
    }

    // Done when the LAST wave has finished crossing.
    let total = wave_attack_ticks(count, beat, shape);
    if ticks >= total {
        end_attack(c, st);
    }
}

/// A held note: the rope is reeled in while the chord sustains.
///
/// This is the attack that uses the rope itself. `rope_len` is re-projected by
/// the engine every frame, so shortening it drags the player up their own
/// tether toward whatever they are attached to — which is a threat they answer
/// by letting go, in a fight that is already about letting go at the right
/// moment.
fn run_sustain(c: &mut Canvas, st: &Arc<Mutex<State>>, ticks: u32) {
    {
        let mut s = st.lock().unwrap();
        if s.hooked {
            s.rope_len = (s.rope_len - CONDUCTOR_SUSTAIN_REEL).max(CONDUCTOR_SUSTAIN_MIN_LEN);
        }
    }
    if ticks >= CONDUCTOR_SUSTAIN_TICKS {
        end_attack(c, st);
    }
}

/// The bar accelerates to a peak; on the last beat every node rings and drops
/// anyone still attached who has not been keeping time.
fn run_crescendo(
    c: &mut Canvas,
    st: &Arc<Mutex<State>>,
    ticks: u32,
    _player: (f32, f32),
    _core: (f32, f32),
) {
    const LEN: u32 = 150;
    {
        let mut s = st.lock().unwrap();
        // Squeeze the beat toward half its length across the attack, then the
        // peak. The player hears and SEES the tempo climb, which is the tell.
        let t = (ticks as f32 / LEN as f32).min(1.0);
        let base = CONDUCTOR_BEAT_TICKS_P2 as f32;
        s.boss_beat_interval = (base * (1.0 - 0.45 * t)).round().max(8.0) as u32;
    }
    if ticks >= LEN {
        let drop_them = {
            let s = st.lock().unwrap();
            // Only drops a player who is attached AND out of time. Keeping
            // Resonance up is the counterplay, which rewards the thing the
            // fight is teaching instead of being an unavoidable tax.
            s.hooked && s.boss_resonance == 0
        };
        if drop_them {
            c.run(Action::ReleaseGrapple { target: Target::name("player") });
        }
        end_attack(c, st);
    }
}

/// Retire the running attack and put its pieces away.
fn end_attack(c: &mut Canvas, st: &Arc<Mutex<State>>) {
    {
        let mut s = st.lock().unwrap();
        s.conductor_attack = 0;
        s.conductor_attack_ticks = 0;
        s.conductor_telegraph = 0;
        s.conductor_bar_hit = false;
        s.conductor_wave_hit = 0;
        s.conductor_wave_count = 1;
    }
    for i in 0..2 {
        for half in ["top", "bot"] {
            if let Some(o) = c.get_game_object_mut(&format!("conductor_bar_{i}_{half}")) {
                o.visible = false;
                o.size = (CONDUCTOR_DORMANT, CONDUCTOR_DORMANT);
                o.position = (-9000.0, -9000.0);
            }
        }
    }
    // Stop every node ringing. Unconditionally, and taken from the list so a
    // node that has since been recycled is still released.
    let ringing = std::mem::take(&mut st.lock().unwrap().conductor_ring_fx);
    for id in ringing {
        c.clear_effect(&id);
    }
}

/// Full Resonance opens the core. Touching it while it is open damages it.
///
/// NO BUFF REQUIRED, unlike every other boss. Stacking "carry a buff" on top of
/// "land three on-beat releases" and "reach the core inside three seconds" gave
/// the fight three simultaneous conditions and no way to see any of them — the
/// honest report from playing it was "how do you actually damage this?".
/// Resonance IS this boss's key; that is what makes the rhythm matter.
fn tick_weakpoint(
    c: &mut Canvas,
    st: &Arc<Mutex<State>>,
    buffed: bool,
    core: (f32, f32),
    player: (f32, f32),
) {
    let (open, window) = {
        let s = st.lock().unwrap();
        // The TIMER alone. This used to also require the meter to still be
        // full, while the meter being full re-armed the timer on every beat —
        // between them the window never actually expired, and the fight's
        // "vulnerable period" lasted until the player happened to land a hit.
        // `CONDUCTOR_WINDOW_TICKS` was therefore a number that did nothing.
        (s.boss_flare_window_ticks > 0, s.boss_flare_window_ticks)
    };

    // ── Show the weakpoint, at exactly the radius that works ──
    if let Some(o) = c.get_game_object_mut("conductor_weak_zone") {
        if open {
            let d = CONDUCTOR_WEAK_R * 2.0;
            o.size = (d, d);
            o.position = (core.0 - d * 0.5, core.1 - d * 0.5);
            o.visible = true;
            // Pulses, and brightens as the window runs out, so "hurry" is
            // legible without a number.
            let urgency = 1.0 - (window as f32 / CONDUCTOR_WINDOW_TICKS as f32).clamp(0.0, 1.0);
            let beat = ((window as f32 * 0.35).sin().abs() * 60.0) as u8;
            o.set_tint(Color(255, 255, 255, (170 + beat as u32).min(255) as u8));
            // No glow: the marker below carries the state, in the same reticle
            // geometry every other boss uses for "hit me now".
            o.clear_glow();
        } else {
            o.visible = false;
            o.size = (CONDUCTOR_DORMANT, CONDUCTOR_DORMANT);
            o.clear_highlight();
        }
    }
    {
        let d = CONDUCTOR_WEAK_R * 2.0;
        if open {
            let urgency = 1.0 -
                (window as f32 / CONDUCTOR_WINDOW_TICKS as f32).clamp(0.0, 1.0);
            crate::scenes::game::fx::attach_state_marker(
                c, "conductor_weak_zone", (d, d),
                MARKER_VULNERABLE_RGB, (0.75 + 0.25 * urgency).min(1.0),
                MarkerMode::Vulnerable);
        } else {
            c.clear_effect("conductor_weak_zone");
        }
    }

    if !open {
        return;
    }
    if (player.0 - core.0).powi(2) + (player.1 - core.1).powi(2)
        >= CONDUCTOR_WEAK_R * CONDUCTOR_WEAK_R
    {
        return;
    }

    // Double with a buff in hand. The buff is optional power here rather than
    // the price of entry: ten clean cycles to kill it unbuffed, five if you
    // arrive carrying one — and the buff is also the shield, so spending it to
    // survive costs you that.
    let damage = if buffed { 4 } else { 2 };
    // Confirm the hit on the core itself. A buffed hit does double damage, so
    // it gets a bigger burst — the feedback reports the SIZE of what landed,
    // not merely that something did.
    crate::scenes::game::boss::common::spawn_impact(
        c, st, core,
        CONDUCTOR_CORE_SIZE * if buffed { 0.85 } else { 0.6 },
        if buffed { CONDUCTOR_METER_ARMED_RGB } else { CONDUCTOR_TARGET_RGB },
        false);
    let hp = {
        let mut s = st.lock().unwrap();
        s.boss_hp = (s.boss_hp - damage).max(0);
        s.buff_hit_flash = 20;
        // Stacks are SPENT on the hit, so the loop restarts rather than one
        // good bar paying out for the rest of the fight.
        s.boss_resonance = 0;
        s.boss_flare_window_ticks = 0;
        s.boss_hp
    };
    if let Some(cam) = c.camera_mut() {
        let (tint, amp) = if buffed {
            (Color(255, 240, 150, 170), 0.45)
        } else {
            (Color(150, 240, 235, 120), 0.30)
        };
        cam.flash_with(tint, amp, FlashMode::Pulse, FlashEase::Sharp, 0.7, 0.0);
    }
    if hp <= 0 {
        hide_conductor(c);
        if let Some(obj) = c.get_game_object_mut("boss") {
            obj.visible = false;
            obj.position = (-6000.0, -6000.0);
        }
        finish_boss(c, st);
    }
}

/// Touching the case costs a heart, at most once per `CONDUCTOR_CONTACT_COOLDOWN`.
///
/// The cooldown is the whole point of this function existing separately.
/// `lose_heart` has no invulnerability of its own, so calling it on a raw
/// overlap test takes every heart in the run within a few frames of a single
/// bump — which is what all four of the unfinished bosses did.
/// Mark every tether node on the approach to a scoring beat.
///
/// ## Why the nodes and not just the readouts
///
/// The player is LOOKING AT A NODE when they decide to release — that is where
/// their hand and their attention are. Every cue for "this is the beat" lived
/// somewhere else: the field at the screen edges, the meter, the spars around
/// the boss. Worse, the field's colour was doing double duty, so the instant a
/// wave was announced it turned red and the only "release now" cue on screen
/// disappeared into the warning.
///
/// So the beat gets its own channel, on the thing the player is holding, in a
/// shape that closes INWARD — the opposite of the wave's outward sonic ring.
/// A node never shows both: a node a wave is about to strike is not a node to
/// be holding, whatever the beat is doing.
fn tick_beat_nodes(c: &mut Canvas, st: &Arc<Mutex<State>>, on_target: f32) {
    let (nodes, ringing, marked) = {
        let s = st.lock().unwrap();
        (s.live_hooks.clone(), s.conductor_ring_fx.clone(),
         s.conductor_beat_fx.clone())
    };
    let show = on_target > 0.02;
    let mut now: Vec<String> = Vec::new();
    if show {
        for id in &nodes {
            // Never over a node the wave already owns.
            if ringing.contains(id) {
                continue;
            }
            let r = match c.get_game_object(id) {
                Some(o) => o.size.0.max(o.size.1) * 0.5,
                None => continue,
            };
            let d = r * CONDUCTOR_BEAT_NODE_SCALE;
            c.attach_effect(
                id, Effect::BeatNode { near: on_target },
                crate::scenes::game::fx::lin(CONDUCTOR_BEAT_NODE_RGB), (d, d));
            now.push(id.clone());
        }
    }
    // Clear anything that was marked last frame and is not now, so a node the
    // wave has taken over, or one that has been recycled, never keeps the cue.
    for id in &marked {
        if !now.contains(id) {
            c.clear_effect(id);
        }
    }
    st.lock().unwrap().conductor_beat_fx = now;
}

/// The close-range guard: a circular graphic equaliser around the core.
///
/// ## Why it exists
///
/// The Conductor does not move. Without something here the strongest play is
/// to park on the nearest node and wait out the fight — and that is not a
/// theory: the headless bot does exactly that and takes ZERO damage across
/// 4000 frames with the whole fight running.
///
/// ## What it asks
///
/// Four quadrant arcs push outward from the core on the beat, loudest on the
/// kicks. Being inside a travelling arc throws you out and costs a heart. So
/// close range is a place you pass THROUGH rather than sit in.
///
/// ## Why it switches off
///
/// It is disabled entirely while the weakpoint is open. The reward for reading
/// seven kicks correctly should be a clear run at the core, not one more thing
/// to dodge on the way in — the fight's shape is "earn the opening, then take
/// it", and a guard that stayed up would blunt both halves.
fn tick_eq_guard(
    c: &mut Canvas,
    st: &Arc<Mutex<State>>,
    core: (f32, f32),
    player: (f32, f32),
    beat_landed: bool,
    on_target: f32,
) {
    let (levels, open, dist) = {
        let mut s = st.lock().unwrap();
        let open = s.boss_flare_window_ticks > 0;

        // Decay every quadrant, then push the ones this beat drives.
        for l in s.conductor_eq.iter_mut() {
            *l = (*l - CONDUCTOR_EQ_DECAY).max(0.0);
        }
        if beat_landed && !open {
            // Which quadrants fire is stepped by the bar, so the guard sweeps
            // round rather than pulsing symmetrically — a symmetric ring gives
            // the player no side to escape toward.
            let base = (s.conductor_beat_in_bar as usize) % 4;
            let strength = 0.72 + 0.28 * on_target;
            s.conductor_eq[base] = strength;
            s.conductor_eq[(base + 2) % 4] = strength * 0.55;
        }
        if s.conductor_eq_cd > 0 {
            s.conductor_eq_cd -= 1;
        }
        let dx = player.0 - core.0;
        let dy = player.1 - core.1;
        (s.conductor_eq, open, (dx * dx + dy * dy).sqrt())
    };

    // ── Draw ──
    if let Some(o) = c.get_game_object_mut("conductor_eq") {
        let live = !open && levels.iter().any(|l| *l > 0.01);
        if live {
            let d = CONDUCTOR_EQ_R * 2.0;
            o.size = (d, d);
            o.position = (core.0 - CONDUCTOR_EQ_R, core.1 - CONDUCTOR_EQ_R);
            o.visible = true;
        } else {
            o.visible = false;
            o.size = (CONDUCTOR_DORMANT, CONDUCTOR_DORMANT);
            o.position = (-9000.0, -9000.0);
        }
    }
    if !open && levels.iter().any(|l| *l > 0.01) {
        c.attach_effect(
            "conductor_eq", Effect::EqArcs { intensity: 1.0, levels },
            crate::scenes::game::fx::lin(CONDUCTOR_EQ_RGB),
            (CONDUCTOR_EQ_R * 2.0, CONDUCTOR_EQ_R * 2.0));
    } else {
        c.clear_effect("conductor_eq");
    }

    if open {
        return;
    }

    // ── Hit ──
    //
    // Which quadrant the player is in decides which arc can reach them, so
    // standing in a quiet quadrant is a real answer to the guard.
    let q = {
        let ang = (player.1 - core.1).atan2(player.0 - core.0)
            + std::f32::consts::PI;
        ((ang / std::f32::consts::FRAC_PI_2) as usize) % 4
    };
    let level = levels[q];
    if level <= 0.01 {
        return;
    }
    let arc_r = level * CONDUCTOR_EQ_R;
    let band = CONDUCTOR_EQ_R * CONDUCTOR_EQ_BAND;
    if (dist - arc_r).abs() > band {
        return;
    }

    let fire = {
        let mut s = st.lock().unwrap();
        if s.conductor_eq_cd > 0 {
            false
        } else {
            s.conductor_eq_cd = CONDUCTOR_EQ_COOLDOWN;
            true
        }
    };
    if !fire {
        return;
    }

    // Thrown OUT, and released. Being pushed off the core is the lesson; being
    // left attached to a node inside the guard would just repeat the hit.
    let len = dist.max(1.0);
    let (nx, ny) = ((player.0 - core.0) / len, (player.1 - core.1) / len);
    {
        let mut s = st.lock().unwrap();
        s.vx += nx * CONDUCTOR_EQ_KNOCK;
        s.vy += ny * CONDUCTOR_EQ_KNOCK;
    }
    c.run(Action::ReleaseGrapple { target: Target::name("player") });
    hit_player(c, st);
}

fn tick_contact(c: &mut Canvas, st: &Arc<Mutex<State>>, core: (f32, f32), player: (f32, f32)) {
    // Tick the cooldown down, and report only whether the bodies overlap.
    //
    // This used to SET the cooldown as well, and then call `hit_player` — which
    // checks the cooldown and found the one just set, so touching the body
    // never cost anything at all. `hit_player` owns the gate; everything else
    // only reports contact.
    let touching = {
        let mut s = st.lock().unwrap();
        if s.boss_contact_cooldown > 0 {
            s.boss_contact_cooldown -= 1;
            false
        } else {
            let r = PLAYER_R + CONDUCTOR_CORE_SIZE * 0.5;
            (player.0 - core.0).powi(2) + (player.1 - core.1).powi(2) < r * r
        }
    };
    if touching {
        hit_player(c, st);
    }
}

/// One source of damage, so the cooldown cannot be bypassed by a new attack
/// forgetting to check it.
///
/// A live buff ABSORBS the hit and is spent doing it. The buff is not required
/// to damage this boss, so without a job here it would be worth nothing in the
/// fight; as a one-shot shield it is a real choice — hold it for the extra
/// damage, or spend it surviving a mistake.
fn hit_player(c: &mut Canvas, st: &Arc<Mutex<State>>) {
    enum Outcome { Nothing, Absorbed, Hurt }
    let outcome = {
        let mut s = st.lock().unwrap();
        if s.boss_contact_cooldown > 0 {
            Outcome::Nothing
        } else {
            s.boss_contact_cooldown = CONDUCTOR_CONTACT_COOLDOWN;
            if s.buff_active() {
                // Spent entirely, not decremented: one attack, then gone.
                s.retire_buff();
                s.buff_hit_flash = 20;
                Outcome::Absorbed
            } else {
                Outcome::Hurt
            }
        }
    };
    match outcome {
        Outcome::Nothing => {}
        Outcome::Absorbed => {
            // Cyan rather than red: a shield spent is not damage taken, and the
            // player has to be able to tell those apart instantly.
            if let Some(cam) = c.camera_mut() {
                cam.flash_with(Color(120, 235, 255, 110), 0.3, FlashMode::Pulse,
                               FlashEase::Sharp, 0.8, 0.0);
            }
        }
        Outcome::Hurt => {
            crate::scenes::game::hearts::lose_heart(c, st);
        }
    }
}

/// Everything the player reads the fight by.
fn draw_conductor(c: &mut Canvas, st: &Arc<Mutex<State>>, core: (f32, f32)) {
    let (beat_ticks, interval, beat_in_bar, resonance, telegraph, window, waves,
         on_target, wave_warning) = {
        let s = st.lock().unwrap();
        let pos = loop_slot_position(
            s.conductor_loop_bar, s.conductor_beat_in_bar, s.conductor_beat_phase);
        // A wave is coming, or one is crossing right now. Either way the
        // player's job for the next second is to be off a node, not to score,
        // and the screen says so in a colour that means nothing else.
        let warning = (s.conductor_attack == 1 && s.conductor_telegraph > 0)
            || (s.conductor_attack == 1 && s.conductor_telegraph == 0);
        (s.boss_beat_ticks, s.boss_beat_interval.max(1), s.conductor_beat_in_bar,
         s.boss_resonance, s.conductor_telegraph, s.boss_flare_window_ticks,
         s.conductor_wave_count.max(1), kick_proximity(pos), warning)
    };
    // 0 at the beat, rising to 1 just before the next.
    let since = 1.0 - (beat_ticks as f32 / interval as f32);

    // ── Channel one: the bob crosses the scale, one sweep per beat ──
    // Alternating direction each beat makes it a metronome rather than a
    // repeating twitch, and gives the eye a position to read, not just motion.
    let dir = if beat_in_bar % 2 == 0 { 1.0 } else { -1.0 };
    let swing = (since * std::f32::consts::PI).sin() * dir;
    if let Some(o) = c.get_game_object_mut("conductor_bob") {
        let bd = o.size.0;
        o.position = (
            core.0 + swing * CONDUCTOR_CORE_SIZE * 0.22 - bd * 0.5,
            core.1 - CONDUCTOR_CORE_SIZE * 0.12 - bd * 0.5,
        );
    }

    // ── Channel two: the spars ring on the beat ──
    // Brightness spikes at the beat and decays, so a glance at any spar says
    // how long ago the beat was.
    let ring_a = (1.0 - since).powi(3);
    let mut spar_fx: Vec<(String, f32)> = Vec::new();
    for i in 0..CONDUCTOR_SPARS {
        let ang = std::f32::consts::TAU * (i as f32 / CONDUCTOR_SPARS as f32)
            + since * 0.10;
        let sx = core.0 + ang.cos() * CONDUCTOR_SPAR_R;
        let sy = core.1 + ang.sin() * CONDUCTOR_SPAR_R;
        if let Some(o) = c.get_game_object_mut(&format!("conductor_spar_{i}")) {
            o.position = (sx - o.size.0 * 0.5, sy - o.size.1 * 0.5);
            o.rotation = ang.to_degrees() + 90.0;
            // NO GLOW AT ALL, of any shape.
            //
            // A glow is a stroke around the object's bounds, so on a spar it
            // was first a teal square and then — once the engine stopped
            // handing out square glows — a white circle. Neither is a tuning
            // fork ringing; both are a halo sitting behind a sprite.
            //
            // What a struck fork does is emit, so it emits: the sonic rings
            // below travel outward from it on the beat. The tint is kept as a
            // brightness lift so the fork itself still answers the beat.
            o.clear_glow();
            let k = (150.0 + 105.0 * ring_a) as u8;
            o.set_tint(Color(255, 255, 255, k.max(150)));
            spar_fx.push((format!("conductor_spar_{i}"), o.size.0.max(o.size.1)));
        }
    }
    // Outside the borrow: the effect helpers take the canvas too.
    for (name, size) in spar_fx {
        c.attach_effect(
            &name,
            Effect::SonicRing {
            // Pulses on the beat over a floor that never goes quiet.
            //
            // This used to fall to 0.25 between beats, and with the ring's
            // sharp front and its rim falloff that reads as the effect
            // STOPPING rather than breathing — a fork that rings on the beat
            // and is silent between looks broken, where a fork that is always
            // ringing and swells on the beat looks alive.
                intensity: (0.55 + 0.45 * ring_a).min(1.0),
            },
            crate::scenes::game::fx::lin(CONDUCTOR_SPAR_FX_RGB),
            (size * CONDUCTOR_SPAR_FX_SCALE, size * CONDUCTOR_SPAR_FX_SCALE),
        );
    }

    // ── The core's own state ──
    //
    // A fourth channel for "the boss is open", on the boss itself. The others
    // (the weakpoint marker, the gold field, the meter) are all AROUND the
    // core; a player looking straight at the thing they are about to hit
    // should not have to look away to learn they can hit it.
    {
        let want_vuln = window > 0;
        let changed = {
            let mut s = st.lock().unwrap();
            let c = s.conductor_core_vuln != want_vuln;
            s.conductor_core_vuln = want_vuln;
            c
        };
        if changed {
            let bytes = if want_vuln { ASSET_PL_CORE_VULNERABLE } else { ASSET_PL_CORE };
            if let Some(img) = crate::scenes::game::helpers::pl_image(bytes, CONDUCTOR_CORE_SIZE) {
                if let Some(o) = c.get_game_object_mut("conductor_core") {
                    // Drop the idle loop while open: `update_animation`
                    // rebuilds `drawable` from the sprite every frame, so a
                    // running animation would overwrite this image immediately
                    // and the swap would never be visible.
                    o.animated_sprite = if want_vuln {
                        None
                    } else {
                        crate::scenes::game::helpers::pl_sprite(
                            &ASSET_PL_CORE_IDLE, CONDUCTOR_CORE_SIZE, PL_CORE_IDLE_FPS)
                    };
                    o.set_image(Image {
                        shape: ShapeType::Rectangle(0.0, (CONDUCTOR_CORE_SIZE, CONDUCTOR_CORE_SIZE), 0.0),
                        image: img.into(),
                        color: None,
                    });
                }
            }
        }
    }

    // ── The downbeat ring ──
    // Scaled from one texture rather than redrawn per frame: an image rebuilt
    // every frame is a texture upload every frame.
    {
        let show = beat_in_bar == 0 && beat_ticks + CONDUCTOR_RING_TICKS >= interval;
        if let Some(o) = c.get_game_object_mut("conductor_beat_ring") {
            if show {
                let age = interval - beat_ticks;
                let t = (age as f32 / CONDUCTOR_RING_TICKS as f32).min(1.0);
                let d = (CONDUCTOR_RING_MAX_R * 2.0) * (0.15 + 0.85 * t);
                o.size = (d, d);
                o.position = (core.0 - d * 0.5, core.1 - d * 0.5);
                o.visible = true;
                o.set_tint(Color(255, 255, 255, (210.0 * (1.0 - t)) as u8));
            } else {
                o.visible = false;
                o.size = (CONDUCTOR_DORMANT, CONDUCTOR_DORMANT);
            }
        }
    }

    // ── Beat field: the whole screen keeps time ─────────────────────
    //
    // Always on, for the whole fight. The beat is the one thing the player
    // must never lose, and a readout in a corner can be missed while looking
    // at a node — so it is carried at the edges of the view, fading to nothing
    // through the middle where the player is aiming.
    //
    // It also reports the state: the same colour swing the meter uses, so
    // "vulnerable" arrives across the entire screen rather than as a detail.
    {
        // The window ALONE. Resonance is spent the moment the window opens, so
        // reading the meter here would turn every "vulnerable" visual off at
        // exactly the moment it is supposed to be shouting.
        let armed = window > 0;
        // Snaps bright on the beat and falls away, so the pulse is the beat
        // rather than a general shimmer. Cubed, to make the attack sharp.
        let pulse = ring_a.powi(2) * if beat_in_bar == 0 { 1.0 } else { 0.62 };

        // THREE states, and they are three colours, because the player has to
        // tell them apart at a glance while aiming at something else:
        //
        //   warning  — a wave is coming or crossing. Do not be attached.
        //   armed    — the core is open. Go and hit it.
        //   target   — a kick is landing. THIS is the one to release on.
        //
        // Before this, every beat was drawn identically, so which beats were
        // targets could only be heard. That is the complaint the kick map was
        // supposed to answer and the visuals were still answering the old way.
        let (rgb, strength) = if wave_warning {
            (CONDUCTOR_WARN_RGB, (0.60 + 0.40 * pulse).min(1.0))
        } else if armed {
            (CONDUCTOR_METER_ARMED_RGB, (0.55 + 0.45 * pulse).min(1.0))
        } else if on_target > 0.02 {
            // Rises INTO the kick and falls away after, so it can be
            // anticipated rather than only confirmed.
            (CONDUCTOR_TARGET_RGB, (0.30 + 0.70 * on_target).min(1.0))
        } else {
            (CONDUCTOR_METER_BUILD_RGB, pulse * 0.55)
        };

        // ONE full-screen quad. The four edge strips are kept in the scene but
        // parked: four strips at full depth is four overlapping full-screen
        // passes for the same picture, and the vignette in the shader already
        // keeps the middle of the view clear.
        // Sized to the REAL screen, not the virtual canvas.
        //
        // `VW`/`VH` are 3840x2160 — 16:9. The phone is 2712x1220, about
        // 2.22:1, so the virtual canvas is pillarboxed inside the real one and
        // a field sized to it stops short of the physical edges with black
        // beyond. Centred on the virtual canvas so the overflow is even.
        let (fw, fh) = c.actual_size_virtual();
        let (fx, fy) = ((VW - fw) * 0.5, (VH - fh) * 0.5);
        if let Some(o) = c.get_game_object_mut("conductor_field_top") {
            o.size = (fw, fh);
            o.position = (fx, fy);
            o.visible = true;
        }
        c.attach_effect(
            "conductor_field_top", Effect::BeatField { pulse: strength, edge: ScreenEdge::All },
            crate::scenes::game::fx::lin(rgb), (fw, fh));
        for name in ["conductor_field_bot", "conductor_field_left",
                     "conductor_field_right"] {
            if let Some(o) = c.get_game_object_mut(name) {
                o.visible = false;
                o.size = (CONDUCTOR_DORMANT, CONDUCTOR_DORMANT);
            }
            c.clear_effect(name);
        }
    }

    // ── Resonance meter ─────────────────────────────────────────────
    //
    // Amplitude is the charge and colour is the state: it swings from the
    // building colour to the armed one at the threshold, so the moment the
    // boss becomes vulnerable is announced by the readout the player is
    // already watching rather than by a separate cue they have to learn.
    {
        let req = CONDUCTOR_RESONANCE_REQUIRED.max(1) as f32;
        let charge = (resonance as f32 / req).clamp(0.0, 1.0);
        // The window ALONE. Resonance is spent the moment the window opens, so
        // reading the meter here would turn every "vulnerable" visual off at
        // exactly the moment it is supposed to be shouting.
        let armed = window > 0;

        // Armed: full amplitude with a pulse, so it is alive rather than
        // simply full. Building: the charge itself, with a small kick on each
        // beat so the meter visibly answers the rhythm.
        let amp = if armed {
            0.85 + 0.15 * (window as f32 * 0.30).sin().abs()
        } else {
            (charge * 0.92 + 0.08 * ring_a * charge).min(1.0)
        };
        let rgb = if armed { CONDUCTOR_METER_ARMED_RGB } else { CONDUCTOR_METER_BUILD_RGB };

        if let Some(o) = c.get_game_object_mut("conductor_meter") {
            o.size = (CONDUCTOR_METER_W, CONDUCTOR_METER_H);
            o.position = (VW * 0.5 - CONDUCTOR_METER_W * 0.5, 210.0);
            o.visible = true;
        }
        c.attach_effect(
            "conductor_meter",
            Effect::ResonanceWave { amplitude: amp },
            crate::scenes::game::fx::lin(rgb),
            (CONDUCTOR_METER_W, CONDUCTOR_METER_H),
        );
    }

    // ── Telegraph and weakpoint states, on the case itself ──
    //
    // `set_glow` strokes the OBJECT'S OWN SHAPE, and the core is a rectangle,
    // so all three of these states used to draw a coloured SQUARE behind the
    // art — the biggest one in the fight. They are markers now: round, and
    // each with its own motion rather than only its own colour.
    let core_state: Option<((f32, f32, f32), f32, MarkerMode)> = if window > 0 {
        // Open: the moment the whole fight is for.
        Some((CONDUCTOR_METER_ARMED_RGB, 1.0, MarkerMode::Vulnerable))
    } else if telegraph > 0 {
        // Winding up — and COUNTING IN. The intensity pulses once per wave
        // that is about to arrive, spread across the telegraph, so a double or
        // a triple can be counted before it lands rather than discovered while
        // you are hanging on a node.
        let t = 1.0 - (telegraph as f32 / (interval as f32 * 2.0)).min(1.0);
        let beats = (t * waves as f32 * std::f32::consts::PI).sin().abs();
        Some((CONDUCTOR_WARN_RGB, (0.55 + 0.45 * beats).min(1.0),
              MarkerMode::WindingUp))
    } else {
        // Resonance is legible at rest: brighter the closer to armed.
        let f = resonance as f32 / CONDUCTOR_RESONANCE_REQUIRED as f32;
        Some((CONDUCTOR_METER_BUILD_RGB, (0.22 + 0.42 * f).min(1.0),
              MarkerMode::Shielded))
    };
    if let Some(o) = c.get_game_object_mut("conductor_core") {
        o.clear_glow();
    }
    // The core already carries its idle/vulnerable sprite as a mega effect
    // slot, so the marker goes on the WEAK ZONE object, which sits concentric
    // with it and is otherwise idle while the core is not open.
    if window == 0 {
        if let Some((rgb, amp, mode)) = core_state {
            let d = CONDUCTOR_CORE_SIZE * 1.25;
            if let Some(o) = c.get_game_object_mut("conductor_weak_zone") {
                o.size = (d, d);
                o.position = (core.0 - d * 0.5, core.1 - d * 0.5);
                o.visible = true;
                o.set_tint(Color(255, 255, 255, 0));
            }
            crate::scenes::game::fx::attach_state_marker(
                c, "conductor_weak_zone", (d, d), rgb, amp, mode);
        }
    }
}

/// Put every Conductor piece away.
///
/// Called when the fight ends and on any frame the boss is not running. The
/// pieces are dedicated objects rather than pooled, so the cost of a miss is a
/// metronome hanging in an empty arena rather than a recycled node wearing the
/// wrong art — but the habit is the same either way: release unconditionally.
pub(crate) fn hide_conductor(c: &mut Canvas) {
    // Give the lane its music back. Index-guarded, so this is a no-op unless a
    // boss loop is actually playing — which makes it safe on the every-frame
    // path and covers death as well as victory.
    crate::scenes::game::switch_game_bgm(c, BGM_TRACK_LANE, ASSET_BGM_TRACK_1, 0.084);

    let mut ids: Vec<String> = vec![
        "conductor_core".into(),
        "conductor_bob".into(),
        "conductor_beat_ring".into(),
    ];
    ids.push("conductor_weak_zone".into());
    for i in 0..CONDUCTOR_SPARS {
        ids.push(format!("conductor_spar_{i}"));
    }
    ids.push("conductor_meter".into());
    for n in ["conductor_field_top", "conductor_field_bot",
              "conductor_field_left", "conductor_field_right"] {
        ids.push(n.into());
    }
    for i in 0..2 {
        for half in ["top", "bot"] {
            ids.push(format!("conductor_bar_{i}_{half}"));
        }
    }
    for id in ids {
        if let Some(o) = c.get_game_object_mut(&id) {
            o.visible = false;
            o.position = (-9000.0, -9000.0);
            o.clear_highlight();
            // Shrink the decorations on the way out; the core and the spars
            // keep their size because the fight re-shows them as they are.
            if id.contains("ring") || id.contains("bar_") || id.contains("weak_zone") {
                o.size = (CONDUCTOR_DORMANT, CONDUCTOR_DORMANT);
            }
            o.clear_mega_fx();
        }
    }
}

#[cfg(test)]
mod kick_targeting_tests {
    use super::*;
    use crate::constants::{CONDUCTOR_BEAT_TICKS, CONDUCTOR_BEAT_TICKS_P2,
                           CONDUCTOR_RELEASE_WINDOW};

    const W: u32 = CONDUCTOR_RELEASE_WINDOW;

    fn tps(interval: u32) -> f32 {
        interval as f32 / CONDUCTOR_SLOTS_PER_BEAT as f32
    }

    /// The property the whole redesign rests on: the snare, the hats and the
    /// plain beats are NOT targets. If this fails the fight is a metronome
    /// again and every click scores.
    #[test]
    fn only_kicks_are_targets() {
        let t = tps(CONDUCTOR_BEAT_TICKS);
        let mut scored = 0;
        let mut ignored = 0;
        for bar in 0..CONDUCTOR_BEATMAP_BARS {
            for slot in 0..CONDUCTOR_SLOTS_PER_BAR {
                let pos = (bar * CONDUCTOR_SLOTS_PER_BAR + slot) as f32;
                let hit = matches!(
                    score_release_slot(pos, t, W), ReleaseScore::Hit { .. });
                if is_kick(bar, slot) {
                    assert!(hit, "bar {bar} slot {slot} is a kick but scored nothing");
                    scored += 1;
                } else {
                    // The other half, and the half that was missing: a
                    // sixteenth that is NOT a kick must not score. One
                    // sixteenth is 9 ticks at 100 BPM and 7.5 at 120, both
                    // outside the +/-6 window, so the nearest non-target is
                    // always out of reach.
                    assert!(!hit,
                            "bar {bar} slot {slot} is not a kick but scored — \
                             every click is a target again");
                    ignored += 1;
                }
            }
        }
        assert_eq!(scored, CONDUCTOR_KICKS_PER_LOOP,
                   "the map and the scorer disagree about how many targets exist");
        assert!(ignored > scored,
                "most sixteenths must NOT be targets — {scored} of \
                 {} were", scored + ignored);
    }

    /// Non-kick sixteenths that are far from any kick must miss outright.
    #[test]
    fn a_release_between_kicks_misses() {
        let t = tps(CONDUCTOR_BEAT_TICKS);
        // Bar 0 is "x.......x.......": slot 4 and slot 12 are as far from a
        // kick as the map ever gets.
        for slot in [4.0_f32, 12.0] {
            assert_eq!(score_release_slot(slot, t, W), ReleaseScore::Miss,
                       "slot {slot} of bar 0 is four sixteenths from any kick");
        }
    }

    /// Symmetric: early and late by the same amount must score the same.
    #[test]
    fn the_window_is_symmetric() {
        let t = tps(CONDUCTOR_BEAT_TICKS);
        let edge = W as f32 / t; // the window, in sixteenths
        for &kick in &[0.0_f32, 8.0] {
            for d in [edge * 0.5, edge * 0.95] {
                assert!(matches!(score_release_slot(kick - d, t, W),
                                 ReleaseScore::Hit { .. }),
                        "early by {d} sixteenths should score");
                assert!(matches!(score_release_slot(kick + d, t, W),
                                 ReleaseScore::Hit { .. }),
                        "late by {d} sixteenths should score");
            }
        }
    }

    /// A release near the END of the loop must find the downbeat on the other
    /// side of the seam, not measure the long way round and call it a miss.
    #[test]
    fn the_loop_seam_is_not_a_dead_zone() {
        let t = tps(CONDUCTOR_BEAT_TICKS);
        let total = loop_slots() as f32;
        let edge = (W as f32 / t) * 0.8;
        assert!(matches!(score_release_slot(total - edge, t, W),
                         ReleaseScore::Hit { .. }),
                "a release just before the loop repeats should hit bar 0's downbeat");
    }

    /// No two kicks are close enough for one release to be ambiguous — the
    /// assumption that lets the window be resolved immediately.
    #[test]
    fn no_two_kicks_fall_inside_one_window() {
        for &interval in &[CONDUCTOR_BEAT_TICKS, CONDUCTOR_BEAT_TICKS_P2] {
            let t = tps(interval);
            let mut prev: Option<u32> = None;
            for bar in 0..CONDUCTOR_BEATMAP_BARS {
                for slot in 0..CONDUCTOR_SLOTS_PER_BAR {
                    if !is_kick(bar, slot) { continue; }
                    let g = bar * CONDUCTOR_SLOTS_PER_BAR + slot;
                    if let Some(p) = prev {
                        let gap_ticks = (g - p) as f32 * t;
                        assert!(gap_ticks > W as f32 * 2.0,
                                "kicks at {p} and {g} are {gap_ticks:.1} ticks apart, \
                                 inside one +/-{W} tick window at interval {interval}");
                    }
                    prev = Some(g);
                }
            }
        }
    }

    /// The position function must agree with the plain slot arithmetic.
    #[test]
    fn loop_position_lands_on_the_right_sixteenth() {
        // Bar 2, beat 0, a quarter of the way through = bar 2's "1-e".
        let pos = loop_slot_position(2, 0, 0.25);
        assert!((pos - (2.0 * 16.0 + 1.0)).abs() < 1e-3, "got {pos}");
        // Bar 0, beat 3, exactly on it = slot 12.
        let pos = loop_slot_position(0, 3, 0.0);
        assert!((pos - 12.0).abs() < 1e-3, "got {pos}");
    }

    /// The wave warning must never land on a target.
    #[test]
    fn the_wave_cue_slot_is_never_a_kick() {
        for bar in 0..CONDUCTOR_BEATMAP_BARS {
            assert!(!is_kick(bar, CONDUCTOR_WAVE_CUE_SLOT),
                    "bar {bar} has a kick on the wave-cue sixteenth, so the \
                     warning would sound like something to hit");
        }
    }

    /// And the whoosh must land OFF the quarter-note grid the kicks sit on.
    /// (`wave_schedule_tests` covers every shape; this is the targeting side.)
    #[test]
    fn the_wave_whoosh_is_off_the_beat() {
        for &interval in &[CONDUCTOR_BEAT_TICKS, CONDUCTOR_BEAT_TICKS_P2] {
            for k in 1..3usize {
                let w = wave_whoosh_tick(k, interval, 0);
                let into_beat = w % interval;
                assert!(into_beat != 0,
                        "wave {k}'s whoosh landed exactly on a beat at interval \
                         {interval}; it must sit on the off-beat");
            }
        }
    }

    /// Quantising to a sixteenth always lands ON that sixteenth, and always in
    /// the future.
    #[test]
    fn quantising_lands_on_the_target_slot() {
        let t = tps(CONDUCTOR_BEAT_TICKS);
        for start in [0.0_f32, 3.7, 13.9, 14.0, 15.5] {
            let d = ticks_to_slot(start, CONDUCTOR_WAVE_CUE_SLOT, t);
            assert!(d >= 1, "a cue must be scheduled in the future, got {d}");
            let landed = (start + d as f32 / t) % CONDUCTOR_SLOTS_PER_BAR as f32;
            let err = (landed - CONDUCTOR_WAVE_CUE_SLOT as f32).abs();
            // The delay is a whole number of ticks, so it cannot land closer
            // than half a tick — about 8ms, well inside anything audible as
            // off-grid. Expressed as the real limit rather than a round number,
            // so this stays honest if the tick rate or the tempo changes.
            let tol = 0.5 / t + 1e-3;
            assert!(err < tol || (CONDUCTOR_SLOTS_PER_BAR as f32 - err) < tol,
                    "from {start} the cue landed on {landed}, not \
                     {CONDUCTOR_WAVE_CUE_SLOT} (tolerance {tol})");
        }
    }
}

#[cfg(test)]
mod eq_guard_tests {
    use crate::constants::*;

    /// Mirrors the quadrant test in `tick_eq_guard`, so the arithmetic that
    /// decides who gets hit is checked rather than described.
    fn quadrant(core: (f32, f32), p: (f32, f32)) -> usize {
        let ang = (p.1 - core.1).atan2(p.0 - core.0) + std::f32::consts::PI;
        ((ang / std::f32::consts::FRAC_PI_2) as usize) % 4
    }

    fn in_band(core: (f32, f32), p: (f32, f32), level: f32) -> bool {
        let dx = p.0 - core.0;
        let dy = p.1 - core.1;
        let dist = (dx * dx + dy * dy).sqrt();
        let arc_r = level * CONDUCTOR_EQ_R;
        (dist - arc_r).abs() <= CONDUCTOR_EQ_R * CONDUCTOR_EQ_BAND
    }

    const CORE: (f32, f32) = (0.0, 0.0);

    /// The point of the whole mechanic: camping ON the boss is punished.
    #[test]
    fn sitting_inside_the_guard_gets_caught() {
        // A pulse sweeping out passes through every radius it covers, so a
        // camper is caught at whatever range they sit at.
        for frac in [0.25_f32, 0.5, 0.75, 0.95] {
            let p = (CONDUCTOR_EQ_R * frac, 0.0);
            let caught = (0..100).any(|i| in_band(CORE, p, i as f32 / 100.0));
            assert!(caught,
                    "a player parked at {frac} of the guard's reach was never \
                     touched by a pulse — camping is still free");
        }
    }

    /// And being properly away from the boss is safe, however loud it gets.
    #[test]
    fn staying_out_of_range_is_safe() {
        let p = (CONDUCTOR_EQ_R * 1.6, 0.0);
        for i in 0..=100 {
            assert!(!in_band(CORE, p, i as f32 / 100.0),
                    "the guard reached past its own radius at level {i}");
        }
    }

    /// The quadrants must actually be four distinct regions, or "stand in the
    /// quiet quadrant" is not an answer the player can use.
    #[test]
    fn the_four_quadrants_are_distinct() {
        let r = CONDUCTOR_EQ_R * 0.5;
        let mut seen = std::collections::HashSet::new();
        for i in 0..4 {
            let a = std::f32::consts::FRAC_PI_2 * i as f32 + 0.3;
            seen.insert(quadrant(CORE, (r * a.cos(), r * a.sin())));
        }
        assert_eq!(seen.len(), 4, "the guard does not have four separate sides: {seen:?}");
    }

    /// A quadrant at zero level must never reach anyone — that is what makes
    /// the sweep readable instead of a constant ring.
    #[test]
    fn a_silent_quadrant_touches_nothing() {
        for frac in [0.3_f32, 0.6, 0.9] {
            let p = (CONDUCTOR_EQ_R * frac, 0.0);
            assert!(!in_band(CORE, p, 0.0),
                    "a quadrant at zero still hit a player at {frac} of reach");
        }
    }

    /// The guard must not reach the weakpoint's own strike radius when it is
    /// at rest, or the approach would be blocked before the arcs even fire.
    #[test]
    fn the_guard_is_wider_than_the_weakpoint() {
        assert!(CONDUCTOR_EQ_R > CONDUCTOR_WEAK_R,
                "the guard ({}) is inside the weakpoint radius ({}) — the \
                 player could never reach the core even when it opens",
                CONDUCTOR_EQ_R, CONDUCTOR_WEAK_R);
    }
}

#[cfg(test)]
mod attack_variety_tests {
    use crate::state::lcg;
    use crate::constants::*;

    /// The bug this exists for: the Conductor's attack and volley rolls were
    /// taken from `boss_phase`, which this fight never advances. Every roll
    /// came out 0, so the sustain and crescendo attacks NEVER FIRED and every
    /// volley was a single wave — three attacks and four volley shapes, all
    /// built and telegraphed and drawn, and the player saw one of each.
    ///
    /// Nothing errored, nothing looked wrong in the code, and no existing test
    /// touched it, because each piece was correct on its own.
    fn roll_attacks(phase2: bool, n: usize) -> Vec<u8> {
        let mut rng = 0x9E37_79B9_7F4A_7C15u64;
        (0..n).map(|_| {
            let r = (lcg(&mut rng) * if phase2 { 3.0 } else { 2.0 }) as u32;
            (r.min(if phase2 { 2 } else { 1 }) + 1) as u8
        }).collect()
    }

    #[test]
    fn phase_one_uses_both_of_its_attacks() {
        let got = roll_attacks(false, 60);
        for want in [1u8, 2] {
            assert!(got.contains(&want),
                    "attack {want} never fired in 60 phase-one bars: {got:?}");
        }
        assert!(!got.contains(&3), "the crescendo is phase two only");
    }

    #[test]
    fn phase_two_uses_all_three() {
        let got = roll_attacks(true, 60);
        for want in [1u8, 2, 3] {
            assert!(got.contains(&want),
                    "attack {want} never fired in 60 phase-two bars: {got:?}");
        }
    }

    /// And the volley size must actually vary, or "sometimes in multiples" is
    /// still a single wave every time.
    #[test]
    fn volleys_come_in_more_than_one_size() {
        let mut rng = 0x9E37_79B9_7F4A_7C15u64;
        let mut sizes = std::collections::HashSet::new();
        for _ in 0..60 {
            let roll = (lcg(&mut rng) * 4.0) as u32 % 4;
            sizes.insert(match roll { 0 => 1u8, 1 | 2 => 2, _ => CONDUCTOR_WAVE_MAX });
        }
        assert!(sizes.len() >= 3,
                "phase two produced only {sizes:?} — volleys never escalate");
    }

    /// The roll must stay in range. `as u32` on a float that reaches 1.0 would
    /// index one past the end.
    #[test]
    fn a_roll_never_escapes_its_range() {
        let mut rng = 1u64;
        for _ in 0..10_000 {
            let r = (lcg(&mut rng) * 3.0) as u32;
            assert!(r <= 3, "roll {r} out of range");
            let shape = (lcg(&mut rng) * 4.0) as u32 % 4;
            assert!((shape as usize) < CONDUCTOR_WAVE_SHAPES.len());
        }
    }
}

#[cfg(test)]
mod wave_schedule_tests {
    use super::{wave_attack_ticks, wave_launch_tick, wave_shape, wave_whoosh_tick};
    use crate::constants::*;

    const SHAPES: usize = CONDUCTOR_WAVE_SHAPES.len();

    /// The requirement in one line: a volley is spaced BY THE BEAT, so every
    /// wave launches on a beat boundary and the player can count them in —
    /// whatever shape the volley takes.
    #[test]
    fn every_wave_launches_on_a_beat() {
        for beat in [CONDUCTOR_BEAT_TICKS, CONDUCTOR_BEAT_TICKS_P2, 24, 18] {
            for shape in 0..SHAPES as u8 {
                for k in 0..CONDUCTOR_WAVE_MAX as usize {
                    let at = wave_launch_tick(k, beat, shape);
                    assert_eq!(
                        at % beat, 0,
                        "shape {shape} wave {k} launches at tick {at}, not a \
                         multiple of the {beat}-tick beat — off the grid"
                    );
                }
            }
        }
    }

    /// The point of the shapes: they must not all be the same volley.
    #[test]
    fn the_shapes_are_actually_different() {
        let beat = CONDUCTOR_BEAT_TICKS;
        let mut seen = std::collections::HashSet::new();
        for shape in 0..SHAPES as u8 {
            let v: Vec<u32> = (0..CONDUCTOR_WAVE_MAX as usize)
                .map(|k| wave_launch_tick(k, beat, shape)).collect();
            assert!(seen.insert(v.clone()),
                    "shape {shape} duplicates another: {v:?} — a volley that \
                     always arrives the same way is the 'one note' complaint");
        }
        assert_eq!(seen.len(), SHAPES);
    }

    /// At least one shape must put two waves a SINGLE beat apart — that is the
    /// back-to-back case the player has to react to quickly.
    #[test]
    fn some_shape_lands_two_waves_back_to_back() {
        let beat = CONDUCTOR_BEAT_TICKS;
        let tight = (0..SHAPES as u8).any(|shape| {
            (1..CONDUCTOR_WAVE_MAX as usize).any(|k| {
                wave_launch_tick(k, beat, shape) - wave_launch_tick(k - 1, beat, shape)
                    == beat
            })
        });
        assert!(tight, "no volley shape puts two waves one beat apart");
    }

    /// And every shape must stay in order — a later wave cannot arrive first.
    #[test]
    fn waves_never_arrive_out_of_order() {
        for shape in 0..SHAPES as u8 {
            let offs = wave_shape(shape);
            for k in 1..offs.len() {
                assert!(offs[k] > offs[k - 1],
                        "shape {shape} offsets {offs:?} are not increasing");
            }
        }
    }

    /// Phase two tightens the tempo, so the same volley must occupy LESS wall
    /// time — the waves follow the music rather than keeping their own clock.
    #[test]
    fn a_faster_tempo_tightens_the_volley() {
        for shape in 0..SHAPES as u8 {
            let slow = wave_attack_ticks(CONDUCTOR_WAVE_MAX, CONDUCTOR_BEAT_TICKS, shape);
            let fast = wave_attack_ticks(CONDUCTOR_WAVE_MAX, CONDUCTOR_BEAT_TICKS_P2, shape);
            assert!(fast < slow,
                    "shape {shape}: a faster tempo did not tighten the volley \
                     ({fast} vs {slow} ticks)");
        }
    }

    /// The attack must outlast its last wave, whatever the shape — ending it
    /// early would leave a band mid-flight and never clear it.
    #[test]
    fn the_attack_outlasts_its_last_wave() {
        for beat in [CONDUCTOR_BEAT_TICKS, CONDUCTOR_BEAT_TICKS_P2] {
            for shape in 0..SHAPES as u8 {
                for count in 1..=CONDUCTOR_WAVE_MAX {
                    let total = wave_attack_ticks(count, beat, shape);
                    let last = wave_launch_tick(count as usize - 1, beat, shape);
                    assert!(total > last,
                            "shape {shape}, {count} waves: attack ends at {total} \
                             but the last wave launches at {last}");
                }
            }
        }
    }

    /// Every whoosh stays OFF the beat, in every shape — that separation from
    /// the kick targets is the whole reason the sound exists.
    #[test]
    fn every_whoosh_is_off_the_beat() {
        for beat in [CONDUCTOR_BEAT_TICKS, CONDUCTOR_BEAT_TICKS_P2] {
            for shape in 0..SHAPES as u8 {
                for k in 0..CONDUCTOR_WAVE_MAX as usize {
                    let w = wave_whoosh_tick(k, beat, shape);
                    // Wave 0 launches at tick 0, so its whoosh is clamped to 0
                    // (there is no time before the attack to play it in).
                    if w == 0 { continue; }
                    assert_ne!(w % beat, 0,
                               "shape {shape} wave {k} whooshes exactly on a \
                                beat at interval {beat}");
                }
            }
        }
    }
}

#[cfg(test)]
mod beat_clock_tests {
    use super::{advance_beat, beat_seconds};
    use crate::constants::*;

    const MAX_DT: f32 = CONDUCTOR_BEAT_MAX_DT;

    /// Run the clock for `secs` of wall time in steps of `dt`, and report how
    /// many beats landed.
    fn beats_over(secs: f32, dt: f32, interval: u32) -> u32 {
        let bs = beat_seconds(interval);
        let mut phase = 0.0;
        let mut beats = 0;
        let steps = (secs / dt).round() as u32;
        for _ in 0..steps {
            let step = advance_beat(phase, dt, bs, MAX_DT);
            phase = step.phase;
            if step.landed {
                beats += 1;
            }
        }
        beats
    }

    /// At a clean 60fps the clock keeps time: 10 seconds at 100 BPM is 16 or
    /// 17 beats (10 / 0.6).
    #[test]
    fn a_clean_frame_rate_keeps_time() {
        let beats = beats_over(10.0, 1.0 / 60.0, CONDUCTOR_BEAT_TICKS);
        assert!(
            (16..=17).contains(&beats),
            "10s at 100 BPM produced {beats} beats, expected ~16.7"
        );
    }

    /// THE BUG. At 20fps — a third of the frames — a tick-counting clock fires
    /// a third as many beats and falls permanently behind the music. Real
    /// elapsed time does not care how many ticks it took.
    #[test]
    fn dropped_frames_do_not_slow_the_beat() {
        let clean = beats_over(10.0, 1.0 / 60.0, CONDUCTOR_BEAT_TICKS);
        let janky = beats_over(10.0, 1.0 / 20.0, CONDUCTOR_BEAT_TICKS);
        assert!(
            (clean as i32 - janky as i32).abs() <= 1,
            "10 seconds produced {clean} beats at 60fps but {janky} at 20fps; \
             the beat is following the frame rate instead of the clock, so it \
             will drift away from the music and the scoring window with it"
        );
    }

    /// An uneven frame rate must not accumulate error either — the remainder
    /// is carried, not dropped.
    #[test]
    fn an_uneven_frame_rate_does_not_accumulate_error() {
        let bs = beat_seconds(CONDUCTOR_BEAT_TICKS);
        let mut phase = 0.0;
        let mut beats = 0;
        let mut elapsed = 0.0f32;
        // Frame times wobbling between 12ms and 28ms, as a real device does.
        let pattern = [0.012f32, 0.028, 0.017, 0.021, 0.014, 0.025];
        for i in 0..3000 {
            let dt = pattern[i % pattern.len()];
            let step = advance_beat(phase, dt, bs, MAX_DT);
            phase = step.phase;
            elapsed += dt;
            if step.landed {
                beats += 1;
            }
        }
        let expected = elapsed / bs;
        assert!(
            (beats as f32 - expected).abs() <= 1.0,
            "after {elapsed:.1}s of uneven frames the clock had counted {beats} \
             beats, expected ~{expected:.1}"
        );
    }

    /// Coming back from a pause must not fire every beat that was missed.
    #[test]
    fn a_long_absence_rebases_instead_of_bursting() {
        let bs = beat_seconds(CONDUCTOR_BEAT_TICKS);
        let step = advance_beat(0.4, 30.0, bs, MAX_DT);
        assert!(step.rebased, "a 30-second gap should re-base the clock");
        assert!(!step.landed, "a re-base must not land a beat");
        assert_eq!(step.phase, 0.4, "the bar should continue where it left off");
    }

    /// And the first tick of a fight, where there is no previous timestamp.
    #[test]
    fn an_unknown_gap_rebases() {
        let bs = beat_seconds(CONDUCTOR_BEAT_TICKS);
        for dt in [f32::INFINITY, f32::NAN, -1.0] {
            let step = advance_beat(0.25, dt, bs, MAX_DT);
            assert!(step.rebased, "dt {dt} should re-base");
            assert_eq!(step.phase, 0.25);
        }
    }

    /// Phase two is faster, so the same wall time holds more beats — the clock
    /// follows the tempo, not the tick count.
    #[test]
    fn a_faster_tempo_fits_more_beats_in_the_same_time() {
        let slow = beats_over(10.0, 1.0 / 60.0, CONDUCTOR_BEAT_TICKS);
        let fast = beats_over(10.0, 1.0 / 60.0, CONDUCTOR_BEAT_TICKS_P2);
        assert!(fast > slow, "120 BPM produced {fast} beats against {slow} at 100");
    }
}

#[cfg(test)]
mod conductor_scale_tests {
    use crate::constants::*;

    /// The Conductor is bigger than the shared body size, and only the
    /// Conductor is. Raising `BOSS_SIZE` instead would have scaled every other
    /// boss's body, hit radii and arena spacing along with it.
    #[test]
    fn the_conductor_has_its_own_larger_body() {
        assert!(CONDUCTOR_CORE_SIZE > BOSS_SIZE,
                "the Conductor ({CONDUCTOR_CORE_SIZE}) is not larger than the \
                 shared body size ({BOSS_SIZE})");
    }

    /// The spars must clear the core, or the ring draws on top of the body it
    /// is supposed to orbit.
    #[test]
    fn the_spars_clear_the_core() {
        let core_r = CONDUCTOR_CORE_SIZE * 0.5;
        let inner_edge = CONDUCTOR_SPAR_R - CONDUCTOR_SPAR_SIZE * 0.5;
        assert!(inner_edge > core_r,
                "spars reach in to {inner_edge} but the core's edge is at \
                 {core_r} — the ring overlaps the body");
    }

    /// The guard has to sit OUTSIDE the weakpoint, or the approach is blocked
    /// even during the window the player earned.
    #[test]
    fn the_guard_still_clears_the_weakpoint() {
        assert!(CONDUCTOR_EQ_R > CONDUCTOR_WEAK_R,
                "guard {CONDUCTOR_EQ_R} is inside the weakpoint \
                 {CONDUCTOR_WEAK_R}");
    }

    /// And the whole thing still has to fit the arena with room to swing.
    #[test]
    fn the_boss_and_its_guard_fit_the_arena() {
        let widest = CONDUCTOR_EQ_R * 2.0;
        assert!(widest < BOSS_ARENA_PLAY_H,
                "the guard spans {widest}, taller than the {BOSS_ARENA_PLAY_H} \
                 play area — there would be nowhere safe to stand");
        assert!(CONDUCTOR_SPAR_R + CONDUCTOR_SPAR_SIZE < BOSS_ARENA_HALF_W,
                "the spar ring reaches past the arena's half width");
    }

    /// The window got easier to hit, which was the point of the change.
    #[test]
    fn the_weakpoint_grew_with_the_boss() {
        let old = BOSS_SIZE * 0.9 + PLAYER_R;
        assert!(CONDUCTOR_WEAK_R > old,
                "the strike radius did not grow: {CONDUCTOR_WEAK_R} vs {old}");
    }
}
